import express from "express";
import QRCode from "qrcode";
import pino from "pino";
import makeWASocket,{DisconnectReason,fetchLatestBaileysVersion,useMultiFileAuthState} from "@whiskeysockets/baileys";
import {createClient} from "@supabase/supabase-js";

const app=express();app.use(express.json({limit:"2mb"}));
const port=Number(process.env.PORT||3100),token=process.env.GATEWAY_TOKEN||"";
const sessions=new Map(),logger=pino({level:process.env.LOG_LEVEL||"warn"});
const safe=id=>String(id).replace(/[^a-zA-Z0-9_-]/g,"");
app.use((req,res,next)=>{if(!token||req.headers.authorization!==`Bearer ${token}`)return res.status(401).json({error:"unauthorized"});next()});

async function connect(org){const id=safe(org);const existing=sessions.get(id);if(existing?.status==="connected"||existing?.status==="connecting")return existing;const state={status:"connecting",qr:null,phone:null,sock:null};sessions.set(id,state);const {state:auth,saveCreds}=await useMultiFileAuthState(`/data/${id}`);const {version}=await fetchLatestBaileysVersion();const sock=makeWASocket({version,auth,logger,printQRInTerminal:false,syncFullHistory:false,markOnlineOnConnect:false,cachedGroupMetadata:async jid=>state.groupCache?.get(jid)});state.sock=sock;state.groupCache=new Map();sock.ev.on("creds.update",saveCreds);sock.ev.on("groups.update",async updates=>{for(const update of updates){try{state.groupCache.set(update.id,await sock.groupMetadata(update.id))}catch{}}});sock.ev.on("connection.update",async update=>{if(update.qr){state.qr=await QRCode.toDataURL(update.qr,{margin:1,width:320});state.status="qr"}if(update.connection==="open"){state.status="connected";state.qr=null;state.phone=sock.user?.id?.split(":")[0]||null}if(update.connection==="close"){const code=update.lastDisconnect?.error?.output?.statusCode;state.status="disconnected";state.sock=null;if(code!==DisconnectReason.loggedOut)setTimeout(()=>connect(id).catch(()=>{}),3000)}});return state}

app.get("/health",(_,res)=>res.json({ok:true}));
app.post("/sessions/:org/connect",async(req,res)=>{try{const s=await connect(req.params.org);res.json({status:s.status,qr:s.qr,phone:s.phone})}catch(e){res.status(500).json({error:e.message})}});
app.get("/sessions/:org/status",(req,res)=>{const s=sessions.get(safe(req.params.org));res.json({status:s?.status||"disconnected",qr:s?.qr||null,phone:s?.phone||null})});
app.delete("/sessions/:org",async(req,res)=>{const s=sessions.get(safe(req.params.org));try{await s?.sock?.logout()}catch{}sessions.delete(safe(req.params.org));res.json({ok:true})});
app.get("/sessions/:org/groups",async(req,res)=>{const s=sessions.get(safe(req.params.org));if(!s?.sock||s.status!=="connected")return res.status(409).json({error:"WhatsApp desconectado"});try{const groups=await s.sock.groupFetchAllParticipating();res.json(Object.values(groups).map(g=>({id:g.id,subject:g.subject,participants:g.participants?.length||0})).sort((a,b)=>a.subject.localeCompare(b.subject)))}catch(e){res.status(500).json({error:e.message})}});
app.post("/sessions/:org/send",async(req,res)=>{const s=sessions.get(safe(req.params.org));if(!s?.sock||s.status!=="connected")return res.status(409).json({error:"WhatsApp desconectado"});try{const {jid,text,mediaUrl}=req.body;let payload={text};if(mediaUrl)payload={video:{url:mediaUrl},caption:text};const result=await s.sock.sendMessage(jid,payload);res.json({ok:true,messageId:result?.key?.id})}catch(e){res.status(500).json({error:e.message})}});

const supabase=process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY?createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}}):null;
let working=false;async function processQueue(){if(!supabase||working)return;working=true;try{const {data:events}=await supabase.from("communication_events").select("id,organization_id,promotion_id,rendered_message,media_url,attempts,promotion_communication_settings!inner(mode,active,group_jid)").eq("status","pending").lte("scheduled_at",new Date().toISOString()).order("scheduled_at").limit(10);for(const event of events||[]){const settings=Array.isArray(event.promotion_communication_settings)?event.promotion_communication_settings[0]:event.promotion_communication_settings;if(!settings?.active||settings.mode!=="automatic"||!settings.group_jid)continue;const s=sessions.get(safe(event.organization_id));if(!s||s.status!=="connected"){await supabase.from("communication_events").update({status:"manual_required",last_error:"WhatsApp desconectado; encaminhada para contingência manual",updated_at:new Date().toISOString()}).eq("id",event.id);continue}try{const response=await fetch(`http://127.0.0.1:${port}/sessions/${event.organization_id}/send`,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({jid:settings.group_jid,text:event.rendered_message,mediaUrl:event.media_url})});if(!response.ok)throw new Error((await response.json()).error||"Falha no envio");await supabase.from("communication_events").update({status:"sent",sent_at:new Date().toISOString(),attempts:event.attempts+1,last_error:null,updated_at:new Date().toISOString()}).eq("id",event.id)}catch(e){await supabase.from("communication_events").update({status:"manual_required",attempts:event.attempts+1,last_error:e.message,updated_at:new Date().toISOString()}).eq("id",event.id)}}}finally{working=false}}
setInterval(()=>processQueue().catch(e=>logger.error(e)),10000);
app.listen(port,"0.0.0.0",()=>logger.info(`gateway on ${port}`));
