"use server";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";

async function gateway(path:string,method="POST",body?:unknown){const base=process.env.WHATSAPP_GATEWAY_URL,token=process.env.WHATSAPP_GATEWAY_TOKEN;if(!base||!token)return;try{await fetch(`${base}${path}`,{method,headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:body?JSON.stringify(body):undefined,cache:"no-store"})}catch{}}

export async function saveTemplate(formData:FormData){const id=String(formData.get("id")||"");const message=String(formData.get("message")||"").trim();const enabled=formData.get("enabled")==="on";if(!message)redirect("/dashboard/comunicacao?error=Mensagem obrigatória");const {error}=await (await createClient()).from("communication_templates").update({message_template:message,enabled,updated_at:new Date().toISOString()}).eq("id",id);if(error)redirect(`/dashboard/comunicacao?error=${encodeURIComponent(error.message)}`);revalidatePath("/dashboard/comunicacao");redirect("/dashboard/comunicacao?saved=1")}
export async function markManualSent(formData:FormData){const id=String(formData.get("id")||"");const {error}=await (await createClient()).from("communication_events").update({status:"sent",sent_manually:true,sent_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id);if(error)redirect(`/dashboard/comunicacao?error=${encodeURIComponent(error.message)}`);revalidatePath("/dashboard/comunicacao")}
export async function setPromotionMode(formData:FormData){const promotionId=String(formData.get("promotionId")||"");const mode=String(formData.get("mode")||"approval"),supabase=await createClient();const {data:promotion}=await supabase.from("promotions").select("organization_id").eq("id",promotionId).maybeSingle();const {error}=await supabase.from("promotion_communication_settings").upsert({promotion_id:promotionId,mode,updated_at:new Date().toISOString()},{onConflict:"promotion_id"});if(error)redirect(`/dashboard/comunicacao?promotion=${promotionId}&error=${encodeURIComponent(error.message)}`);if(mode==="automatic"){await supabase.from("communication_events").update({status:"pending",last_error:null,updated_at:new Date().toISOString()}).eq("promotion_id",promotionId).in("status",["manual_required","failed"]);if(promotion?.organization_id)await gateway(`/sessions/${promotion.organization_id}/process`)}revalidatePath("/dashboard/comunicacao");redirect(`/dashboard/comunicacao?promotion=${promotionId}&saved=1`)}

export async function completePostPurchase(formData:FormData){const id=String(formData.get("id")||"");const promotionId=String(formData.get("promotionId")||"");const action=String(formData.get("action")||"");const supabase=await createClient();const {data:flow,error:flowError}=await supabase.from("post_purchase_flows").select("id,organization_id,phone_e164,reward_type,operator_status").eq("id",id).maybeSingle();if(flowError||!flow)redirect(`/dashboard/comunicacao?promotion=${promotionId}&tab=posvenda&error=${encodeURIComponent(flowError?.message||"Pós-venda não encontrado")}`);const now=new Date().toISOString();let status="",message="";if(action==="pix_paid"&&flow.reward_type==="pix"){status="pix_paid";message="✅ Seu PIX foi realizado. Obrigado por participar e parabéns novamente pelo prêmio!"}else if(action==="product_sent"&&flow.reward_type==="product"){status="product_sent";message="📦 Seu prêmio foi enviado. Obrigado por participar e parabéns novamente!"}else redirect(`/dashboard/comunicacao?promotion=${promotionId}&tab=posvenda&error=${encodeURIComponent("Ação inválida para este pós-venda")}`);const {error}=await supabase.from("post_purchase_flows").update({operator_status:status,operator_completed_at:now,completed_at:now}).eq("id",id);if(error)redirect(`/dashboard/comunicacao?promotion=${promotionId}&tab=posvenda&error=${encodeURIComponent(error.message)}`);await gateway(`/sessions/${flow.organization_id}/send`,"POST",{jid:`${String(flow.phone_e164).replace(/\D/g,"")}@s.whatsapp.net`,text:message});revalidatePath("/dashboard/comunicacao");redirect(`/dashboard/comunicacao?promotion=${promotionId}&tab=posvenda&saved=1`)}
