import Link from "next/link";
import {createClient} from "@/lib/supabase/server";
import styles from "../dashboard.module.css";
import local from "./communication.module.css";
import CopyButton from "./copy-button";
import WhatsAppConnection from "./whatsapp-connection";
import {completePostPurchase,markManualSent,saveTemplate,setPromotionMode} from "./actions";
const labels:Record<string,string>={launch:"Lançamento",first_purchase:"Primeira compra",progress_50:"50% vendido",progress_60:"60% vendido",progress_85:"85% vendido",last_quota:"Última cota",sold_out:"Encerramento",result:"Resultado"};
const postStatus:Record<string,string>={automated:"Fluxo automático",awaiting_pix_contact:"Aguardando contato PIX",awaiting_shipping:"Aguardando envio",pix_paid:"PIX pago",product_sent:"Produto enviado",completed:"Concluído"};
export default async function Page({searchParams}:{searchParams:Promise<{tab?:string;promotion?:string;saved?:string;error?:string}>}){
 const query=await searchParams,tab=query.tab||"fila",supabase=await createClient();
 const {data:auth}=await supabase.auth.getUser();
 const {data:member}=await supabase.from("organization_members").select("organization_id").eq("user_id",auth.user!.id).limit(1).maybeSingle();
 if(!member)return <main className={styles.main}><div className={styles.alertError}>Organização não encontrada.</div></main>;
 const [{data:promotions},{data:templates}]=await Promise.all([
  supabase.from("promotions").select("id,name,status").eq("organization_id",member.organization_id).order("created_at",{ascending:false}),
  supabase.from("communication_templates").select("*").eq("organization_id",member.organization_id).order("created_at")
 ]);
 const promotionId=query.promotion||promotions?.[0]?.id;
 const [{data:events},{data:setting},{data:postFlows}]=promotionId?await Promise.all([
  supabase.from("communication_events").select("*").eq("promotion_id",promotionId).order("created_at",{ascending:false}),
  supabase.from("promotion_communication_settings").select("*").eq("promotion_id",promotionId).maybeSingle(),
  supabase.from("post_purchase_flows").select("id,phone_e164,stage,reward_type,delivery_address,operator_status,last_error,created_at,participants(name),products(name)").eq("promotion_id",promotionId).order("created_at",{ascending:false})
 ]):[{data:[]},{data:null},{data:[]}];
 return <main className={styles.main}>
  <div className={styles.heading}><div><h1>Comunicação</h1><p>Funil do grupo, mensagens automáticas e pós-venda do vencedor.</p></div><form className={local.toolbar}><select name="promotion" defaultValue={promotionId}>{promotions?.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input type="hidden" name="tab" value={tab}/><button className={styles.primary}>Abrir promoção</button></form></div>
  {query.saved?<div className={styles.alertSuccess}>Configuração salva.</div>:null}{query.error?<div className={styles.alertError}>{query.error}</div>:null}
  <div className={local.tabs}><Link className={tab==="fila"?local.active:""} href={`/dashboard/comunicacao?promotion=${promotionId}&tab=fila`}>Fila e contingência</Link><Link className={tab==="modelos"?local.active:""} href={`/dashboard/comunicacao?promotion=${promotionId}&tab=modelos`}>Modelos de mensagens</Link><Link className={tab==="posvenda"?local.active:""} href={`/dashboard/comunicacao?promotion=${promotionId}&tab=posvenda`}>Pós-sorteio / Pós-venda</Link></div>
  {promotionId&&tab==="fila"?<><WhatsAppConnection organizationId={member.organization_id} promotionId={promotionId} currentGroup={setting?.group_jid}/><section className={local.mode}><div><strong>Modo de operação</strong><div>{setting?.group_name?`Grupo: ${setting.group_name}`:"Grupo ainda não conectado"}</div></div><form action={setPromotionMode}><input type="hidden" name="promotionId" value={promotionId}/><select name="mode" defaultValue={setting?.mode||"approval"}><option value="approval">Aprovar antes de enviar</option><option value="manual">Somente copiar e colar</option><option value="automatic">Automático pelo grupo</option></select><button>Salvar</button></form></section><section className={local.queue}>{!events?.length?<div className={styles.panel}><div className={styles.empty}>Os eventos aparecerão aqui conforme a promoção avançar.</div></div>:events.map((e:any)=><article className={local.event} key={e.id}><div className={local.eventStage}><strong>{labels[e.stage]||e.stage}</strong><span>{e.status==="sent"?"Enviada":e.status==="failed"?"Falhou":e.status==="manual_required"?"Requer atenção":"Pendente"}</span></div><p className={local.message}>{e.rendered_message}</p><div className={local.eventActions}><CopyButton text={e.rendered_message}/>{e.media_url?<a href={e.media_url} target="_blank">Baixar mídia</a>:null}{e.status!=="sent"?<form action={markManualSent}><input type="hidden" name="id" value={e.id}/><button>Marcar como enviada</button></form>:null}{e.last_error?<small>Erro: {e.last_error}</small>:null}<small>{new Date(e.created_at).toLocaleString("pt-BR")}</small></div></article>)}</section></>:null}
  {tab==="modelos"?<section className={local.templates}>{templates?.map((t:any)=><form className={local.template} action={saveTemplate} key={t.id}><input type="hidden" name="id" value={t.id}/><h3>{labels[t.stage]||t.title}</h3><textarea name="message" defaultValue={t.message_template}/><footer><label><input type="checkbox" name="enabled" defaultChecked={t.enabled}/> Ativa</label><button>Salvar modelo</button></footer></form>)}</section>:null}
  {promotionId&&tab==="posvenda"?<><section className={styles.panel}><h2>Fluxo de pós-venda</h2><p>Após o resultado, o atendimento privado ao vencedor é automático até a escolha do prêmio. A execução de PIX ou envio do produto é concluída manualmente pelo operador.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12,marginTop:18}}>{["1. Resultado no grupo","2. Parabéns no privado","3. Escolha do produto","4. Produto ou PIX","5. Endereço, se produto","6. Operador conclui"].map((item,index)=><div key={item} style={{padding:14,border:"1px solid #e1e5ef",borderRadius:12,fontWeight:700,background:index<4?"#f7f2ff":"#fff"}}>{item}</div>)}</div></section><section className={styles.panel} style={{marginTop:20}}><h2>Fila operacional</h2>{!postFlows?.length?<div className={styles.empty} style={{marginTop:16}}>Ainda não há vencedor em pós-venda nesta promoção. O fluxo aparecerá aqui automaticamente após o sorteio.</div>:<div style={{display:"grid",gap:14,marginTop:18}}>{postFlows.map((flow:any)=>{const participant=Array.isArray(flow.participants)?flow.participants[0]:flow.participants;const product=Array.isArray(flow.products)?flow.products[0]:flow.products;return <article key={flow.id} style={{padding:18,border:"1px solid #e1e5ef",borderRadius:14}}><div style={{display:"flex",justifyContent:"space-between",gap:16,flexWrap:"wrap"}}><div><strong>{participant?.name||"Vencedor"}</strong><div style={{marginTop:5}}>{flow.phone_e164}</div><div style={{marginTop:5}}>Produto escolhido: {product?.name||"Aguardando escolha"}</div><div style={{marginTop:5}}>Opção: {flow.reward_type==="pix"?"PIX":flow.reward_type==="product"?"Produto":"Aguardando escolha"}</div>{flow.delivery_address?<div style={{marginTop:5}}>Endereço: {flow.delivery_address}</div>:null}{flow.last_error?<div style={{marginTop:5,color:"#b42318"}}>Erro: {flow.last_error}</div>:null}</div><div><strong>{postStatus[flow.operator_status]||flow.operator_status}</strong>{flow.operator_status==="awaiting_pix_contact"?<form action={completePostPurchase} style={{marginTop:10}}><input type="hidden" name="id" value={flow.id}/><input type="hidden" name="promotionId" value={promotionId}/><input type="hidden" name="action" value="pix_paid"/><button className={styles.primary}>Marcar PIX como pago</button></form>:null}{flow.operator_status==="awaiting_shipping"?<form action={completePostPurchase} style={{marginTop:10}}><input type="hidden" name="id" value={flow.id}/><input type="hidden" name="promotionId" value={promotionId}/><input type="hidden" name="action" value="product_sent"/><button className={styles.primary}>Marcar produto como enviado</button></form>:null}</div></div></article>})}</div>}</section></>:null}
 </main>
}
