"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import local from "./communication.module.css";
type Group={id:string;subject:string;participants:number};
export default function WhatsAppConnection({organizationId,promotionId,currentGroup}:{organizationId:string;promotionId?:string;currentGroup?:string|null}){
 const [status,setStatus]=useState("disconnected"),[qr,setQr]=useState<string|null>(null),[phone,setPhone]=useState<string|null>(null),[groups,setGroups]=useState<Group[]>([]),[selected,setSelected]=useState(currentGroup||""),[message,setMessage]=useState(""),[loadingGroups,setLoadingGroups]=useState(false);
 const groupsLoaded=useRef(false);
 const call=useCallback(async(url:string,options?:RequestInit)=>{const response=await fetch(url,options),data=await response.json();if(!response.ok)throw new Error(data.error||"Erro na conexão");return data},[]);
 const loadGroups=useCallback(async(force=false)=>{if(groupsLoaded.current&&!force)return;setLoadingGroups(true);try{const list=await call(`/api/whatsapp?org=${organizationId}&action=groups${force?"&refresh=1":""}`);setGroups(list);groupsLoaded.current=true;setMessage("")}catch(e){const text=e instanceof Error?e.message:"Falha ao carregar grupos";setMessage(text.includes("rate-overlimit")?"O WhatsApp limitou temporariamente a consulta de grupos. Aguarde alguns segundos e tente atualizar.":text)}finally{setLoadingGroups(false)}},[call,organizationId]);
 const refreshStatus=useCallback(async()=>{try{const data=await call(`/api/whatsapp?org=${organizationId}&action=status`);setStatus(data.status);setQr(data.qr);setPhone(data.phone);if(data.status==="connected"&&!groupsLoaded.current)void loadGroups()}catch(e){setMessage(e instanceof Error?e.message:"Falha na conexão")}},[call,organizationId,loadGroups]);
 useEffect(()=>{groupsLoaded.current=false;setGroups([]);void refreshStatus();const timer=setInterval(()=>void refreshStatus(),6000);return()=>clearInterval(timer)},[organizationId,refreshStatus]);
 const connect=async()=>{setMessage("Gerando QR Code...");try{const data=await call("/api/whatsapp",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({org:organizationId,action:"connect"})});setStatus(data.status);setQr(data.qr);setMessage("")}catch(e){setMessage(e instanceof Error?e.message:"Falha")}};
 const saveGroup=async()=>{const group=groups.find(g=>g.id===selected);if(!group||!promotionId)return;try{await call("/api/whatsapp",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({org:organizationId,action:"select_group",promotionId,groupId:group.id,groupName:group.subject})});setMessage(`Grupo ${group.subject} vinculado à promoção.`)}catch(e){setMessage(e instanceof Error?e.message:"Falha")}};
 return <section className={local.connection}><div className={local.connectionHead}><div><strong>WhatsApp do operador</strong><p>{status==="connected"?`Conectado${phone?` • ${phone}`:""}`:status==="qr"?"Aguardando leitura do QR Code":"Desconectado"}</p></div><span className={status==="connected"?local.online:local.offline}>{status==="connected"?"Online":"Offline"}</span></div>{status!=="connected"?<button onClick={connect}>Conectar WhatsApp</button>:null}{qr&&status!=="connected"?<div className={local.qr}><img src={qr} alt="QR Code do WhatsApp"/><p>No celular do operador, abra WhatsApp → Aparelhos conectados → Conectar aparelho.</p></div>:null}{status==="connected"&&promotionId?<><div className={local.groupPicker}><select value={selected} onChange={e=>setSelected(e.target.value)} disabled={loadingGroups}><option value="">{loadingGroups?"Carregando grupos...":"Selecione o grupo da promoção"}</option>{groups.map(g=><option value={g.id} key={g.id}>{g.subject} ({g.participants})</option>)}</select><button onClick={saveGroup} disabled={!selected||loadingGroups}>Vincular grupo</button></div><button type="button" onClick={()=>void loadGroups(true)} disabled={loadingGroups}>{loadingGroups?"Atualizando...":"Atualizar grupos"}</button></>:null}{message?<small>{message}</small>:null}</section>
}
