"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import local from "./communication.module.css";
type Group={id:string;subject:string;participants:number};
type WorkerInfo={configured:boolean;sessionStatus:string;worker:{running:boolean;lastCycleAt:string|null;lastSuccessAt:string|null;lastError:string|null;lastProcessed:number;totalSent:number}};
export default function WhatsAppConnection({organizationId,promotionId,currentGroup}:{organizationId:string;promotionId?:string;currentGroup?:string|null}){
 const router=useRouter();
 const [status,setStatus]=useState("disconnected"),[qr,setQr]=useState<string|null>(null),[phone,setPhone]=useState<string|null>(null),[groups,setGroups]=useState<Group[]>([]),[selected,setSelected]=useState(currentGroup||""),[message,setMessage]=useState(""),[loadingGroups,setLoadingGroups]=useState(false),[savingGroup,setSavingGroup]=useState(false),[worker,setWorker]=useState<WorkerInfo|null>(null),[processing,setProcessing]=useState(false);
 const groupsLoaded=useRef(false);
 const call=useCallback(async(url:string,options?:RequestInit)=>{const response=await fetch(url,options),data=await response.json();if(!response.ok)throw new Error(data.error||"Erro na conexão");return data},[]);
 const loadGroups=useCallback(async(force=false)=>{if(groupsLoaded.current&&!force)return;setLoadingGroups(true);try{const list=await call(`/api/whatsapp?org=${organizationId}&action=groups${force?"&refresh=1":""}`);setGroups(list);groupsLoaded.current=true;setMessage("")}catch(e){const text=e instanceof Error?e.message:"Falha ao carregar grupos";setMessage(text.includes("rate-overlimit")?"O WhatsApp limitou temporariamente a consulta de grupos. Aguarde alguns segundos e tente atualizar.":text)}finally{setLoadingGroups(false)}},[call,organizationId]);
 const refreshStatus=useCallback(async()=>{try{const [data,workerData]=await Promise.all([call(`/api/whatsapp?org=${organizationId}&action=status`),call(`/api/whatsapp?org=${organizationId}&action=worker`)]);setStatus(data.status);setQr(data.qr);setPhone(data.phone);setWorker(workerData);if(data.status==="connected"&&!groupsLoaded.current)void loadGroups()}catch(e){setMessage(e instanceof Error?e.message:"Falha na conexão")}},[call,organizationId,loadGroups]);
 useEffect(()=>{groupsLoaded.current=false;setGroups([]);void refreshStatus();const timer=setInterval(()=>void refreshStatus(),6000);return()=>clearInterval(timer)},[organizationId,refreshStatus]);
 useEffect(()=>{if(currentGroup)setSelected(currentGroup)},[currentGroup]);
 const connect=async()=>{setMessage("Gerando QR Code...");try{const data=await call("/api/whatsapp",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({org:organizationId,action:"connect"})});setStatus(data.status);setQr(data.qr);setMessage("")}catch(e){setMessage(e instanceof Error?e.message:"Falha")}};
 const saveGroup=async()=>{const group=groups.find(g=>g.id===selected);if(!group||!promotionId)return;setSavingGroup(true);try{await call("/api/whatsapp",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({org:organizationId,action:"select_group",promotionId,groupId:group.id,groupName:group.subject})});setMessage(`Grupo ${group.subject} vinculado à promoção.`);router.refresh()}catch(e){setMessage(e instanceof Error?e.message:"Falha")}finally{setSavingGroup(false)}};
 const processNow=async()=>{setProcessing(true);try{await call("/api/whatsapp",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({org:organizationId,action:"process"})});await refreshStatus();router.refresh();setMessage("Fila processada agora.")}catch(e){setMessage(e instanceof Error?e.message:"Falha ao processar fila")}finally{setProcessing(false)}};
 const workerOk=Boolean(worker?.configured&&worker?.sessionStatus==="connected"&&!worker?.worker.lastError);
 return <section className={local.connection}><div className={local.connectionHead}><div><strong>WhatsApp do operador</strong><p>{status==="connected"?`Conectado${phone?` • ${phone}`:""}`:status==="qr"?"Aguardando leitura do QR Code":"Desconectado"}</p></div><span className={status==="connected"?local.online:local.offline}>{status==="connected"?"Online":"Offline"}</span></div>{worker?<div style={{margin:"12px 0",padding:12,borderRadius:12,background:workerOk?"#effaf4":"#fff5f5"}}><strong>Envio automático: {workerOk?"Operacional":"Com problema"}</strong><div style={{marginTop:4,fontSize:14}}>Worker: {worker.worker.running?"processando":"ativo"} • Último ciclo: {worker.worker.lastCycleAt?new Date(worker.worker.lastCycleAt).toLocaleString("pt-BR"):"ainda não executou"} • Total enviado: {worker.worker.totalSent}</div>{worker.worker.lastError?<div style={{marginTop:6}}>Erro: {worker.worker.lastError}</div>:null}<button type="button" onClick={processNow} disabled={processing||status!=="connected"} style={{marginTop:10}}>{processing?"Processando...":"Processar fila agora"}</button></div>:null}{status!=="connected"?<button onClick={connect}>Conectar WhatsApp</button>:null}{qr&&status!=="connected"?<div className={local.qr}><img src={qr} alt="QR Code do WhatsApp"/><p>No celular do operador, abra WhatsApp → Aparelhos conectados → Conectar aparelho.</p></div>:null}{status==="connected"&&promotionId?<><div className={local.groupPicker}><select value={selected} onChange={e=>setSelected(e.target.value)} disabled={loadingGroups||savingGroup}><option value="">{loadingGroups?"Carregando grupos...":"Selecione o grupo da promoção"}</option>{groups.map(g=><option value={g.id} key={g.id}>{g.subject} ({g.participants})</option>)}</select><button onClick={saveGroup} disabled={!selected||loadingGroups||savingGroup}>{savingGroup?"Vinculando...":"Vincular grupo"}</button></div><button type="button" onClick={()=>void loadGroups(true)} disabled={loadingGroups||savingGroup}>{loadingGroups?"Atualizando...":"Atualizar grupos"}</button></>:null}{message?<small>{message}</small>:null}</section>
}
