"use client";
import {useRef,useState} from "react";
import baseStyles from "./draw.module.css";
import workflowStyles from "./workflow.module.css";
import {createClient} from "@/lib/supabase/client";
type Props={drawId:string|null;promotionId:string;promotion:string;imageUrl:string|null;quotaQuantity:number;winningNumber:number|null;winnerName:string|null;resultUrl:string|null;organization:string;logoUrl:string|null|undefined;primaryColor:string;secondaryColor:string};
type Finalized={draw_id:string;winning_number:number;winner_name:string};
type Recording={blob:Blob;type:string;extension:string};
const styles={...baseStyles,...workflowStyles};

export default function DrawExperience(props:Props){
 const [recording,setRecording]=useState(false);const [recorded,setRecorded]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 const [number,setNumber]=useState("");const [resultUrl,setResultUrl]=useState("");
 const [finalized,setFinalized]=useState<Finalized|null>(props.drawId&&props.winningNumber&&props.winnerName?{draw_id:props.drawId,winning_number:props.winningNumber,winner_name:props.winnerName}:null);
 const recorder=useRef<MediaRecorder|null>(null);const capture=useRef<MediaStream|null>(null);const chunks=useRef<Blob[]>([]);const recordedBlob=useRef<Recording|null>(null);

 const uploadVideo=async(draw:Finalized)=>{const saved=recordedBlob.current;if(!saved)throw new Error("A gravação não foi encontrada.");const {blob,type,extension}=saved;const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`resultado-${props.promotion.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-")}.${extension}`;link.click();setMessage("Salvando o vídeo e preparando o envio ao grupo...");const supabase=createClient();const path=`${props.promotionId}/${draw.draw_id}.${extension}`;const {error}=await supabase.storage.from("draw-videos").upload(path,blob,{contentType:type,upsert:true});if(error)throw error;const {data:file}=supabase.storage.from("draw-videos").getPublicUrl(path);const {error:updateError}=await supabase.from("draws").update({video_url:file.publicUrl}).eq("id",draw.draw_id);if(updateError)throw updateError;setMessage("Sorteio concluído. O vídeo entrou na fila de envio do grupo do WhatsApp.");setTimeout(()=>URL.revokeObjectURL(url),1000)};

 const startRecording=async()=>{try{setMessage("");setRecorded(false);recordedBlob.current=null;const stream=await navigator.mediaDevices.getDisplayMedia({video:{displaySurface:"monitor"},audio:false});capture.current=stream;chunks.current=[];const mime=["video/mp4;codecs=avc1","video/webm;codecs=vp9","video/webm;codecs=vp8","video/webm"].find(t=>MediaRecorder.isTypeSupported(t));const mediaRecorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);recorder.current=mediaRecorder;mediaRecorder.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};mediaRecorder.onstop=()=>{const type=mediaRecorder.mimeType||"video/webm";recordedBlob.current={blob:new Blob(chunks.current,{type}),type,extension:type.includes("mp4")?"mp4":"webm"};setRecording(false);setRecorded(true);setMessage("Gravação finalizada. Informe o número sorteado para concluir e enviar o vídeo.")};stream.getVideoTracks()[0].onended=()=>{if(mediaRecorder.state!=="inactive")mediaRecorder.stop()};mediaRecorder.start(500);setRecording(true);setMessage("Gravação iniciada. Agora abra o Sorteador.com.br.")}catch{setMessage("A gravação foi cancelada. Selecione a tela inteira para registrar também a aba do Sorteador.")}};
 const stopRecording=()=>{if(recorder.current?.state!=="inactive")recorder.current?.stop();capture.current?.getTracks().forEach(track=>track.stop())};
 const openSorteador=()=>window.open("https://sorteador.com.br/","_blank","noopener,noreferrer");
 const finish=async()=>{const winning=Number(number);if(!Number.isInteger(winning)||winning<1||winning>props.quotaQuantity){setMessage(`Informe um número entre 1 e ${props.quotaQuantity}.`);return}if(recording){setMessage("Finalize a gravação antes de registrar o resultado.");return}if(!recordedBlob.current){setMessage("Inicie e finalize a gravação antes de registrar o resultado.");return}setBusy(true);setMessage("Validando a cota sorteada...");const supabase=createClient();const {data,error}=await supabase.rpc("finalize_external_promotion_draw",{target_promotion_id:props.promotionId,target_winning_number:winning,target_result_url:resultUrl.trim()||null});if(error){setMessage(error.message);setBusy(false);return}const draw=data as Finalized;setFinalized(draw);try{await uploadVideo(draw)}catch(uploadError){setMessage(`Resultado registrado, mas o vídeo não foi enviado: ${uploadError instanceof Error?uploadError.message:"falha no upload"}`)}finally{setBusy(false)}};

 return <main className={styles.page} style={{"--primary":props.primaryColor,"--secondary":props.secondaryColor} as React.CSSProperties}><div className={styles.orbOne}/><div className={styles.orbTwo}/><section className={styles.stage}>
  <header className={styles.brand}>{props.logoUrl?<img src={props.logoUrl} alt=""/>:<span className={styles.brandMark}>✦</span>}<strong>{props.organization}</strong></header>
  <div className={styles.promo}>{props.imageUrl?<img src={props.imageUrl} alt=""/>:null}<div><span>Sorteio oficial</span><h1>{props.promotion}</h1></div></div>
  <div className={styles.center}>{finalized?<><span className={styles.kicker}>Resultado confirmado no Sorteador.com.br</span><div className={styles.ballWinner}><span>{String(finalized.winning_number).padStart(String(props.quotaQuantity).length,"0")}</span></div><h2 className={styles.winner}>{finalized.winner_name}</h2><p>Parabéns! Esta cota é a grande vencedora.</p>{props.resultUrl?<a className={styles.resultLink} href={props.resultUrl} target="_blank" rel="noreferrer">Conferir resultado externo</a>:null}</>:<div className={styles.workflow}><span className={styles.kicker}>Sorteio externo auditável</span><h2>Realize o sorteio no Sorteador.com.br</h2><ol><li><strong>1.</strong> Inicie a gravação e selecione <b>Tela inteira</b>.</li><li><strong>2.</strong> Abra o Sorteador e configure: <b>1 número entre 1 e {props.quotaQuantity}</b>.</li><li><strong>3.</strong> Volte aqui e clique em <b>Finalizar gravação</b>.</li><li><strong>4.</strong> Informe o resultado para salvar e enviar o vídeo ao grupo.</li></ol><div className={styles.workflowActions}><button onClick={startRecording} disabled={recording}>{recording?"● Gravação em andamento":recorded?"Gravar novamente":"Iniciar gravação"}</button><button className={styles.externalButton} onClick={openSorteador} disabled={!recording}>Abrir Sorteador.com.br ↗</button><button className={styles.stopButton} onClick={stopRecording} disabled={!recording}>Finalizar gravação</button></div><div className={styles.resultForm}><label>Número sorteado<input type="number" min="1" max={props.quotaQuantity} value={number} onChange={e=>setNumber(e.target.value)} placeholder={`1 a ${props.quotaQuantity}`}/></label><label>Link do resultado (opcional)<input type="url" value={resultUrl} onChange={e=>setResultUrl(e.target.value)} placeholder="https://sorteador.com.br/resultado/..."/></label><button onClick={finish} disabled={busy||recording||!recorded}>{busy?"Enviando vídeo...":"Registrar resultado e enviar"}</button></div></div>}</div>
  <footer>Resultado registrado com segurança • {new Date().toLocaleDateString("pt-BR")}</footer>
 </section>{message?<aside className={styles.statusMessage}>{message}</aside>:null}</main>;
}
