"use client";
import {FormEvent,useMemo,useState} from "react";
import {LoaderCircle,Minus,Plus} from "lucide-react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
import styles from "./public-promotion.module.css";
type Props={organizationSlug:string;promotionSlug:string;quotaPrice:number;minimum:number;maximum:number;reservationMinutes:number;disabled:boolean};
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const phone=(v:FormDataEntryValue|null)=>`+55${String(v||"").replace(/\D/g,"").replace(/^55/,"")}`;
export function PurchaseForm(p:Props){const router=useRouter(),[quantity,setQuantity]=useState(p.minimum),[loading,setLoading]=useState(false),[error,setError]=useState("");const total=useMemo(()=>p.quotaPrice*quantity,[p.quotaPrice,quantity]);const add=(n:number)=>setQuantity(v=>Math.min(p.maximum,v+n));async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget),first=phone(f.get("phone")),confirmation=phone(f.get("phoneConfirmation"));if(first!==confirmation){setError("Os números de WhatsApp precisam ser iguais.");return}setLoading(true);const {data,error:err}=await createClient().rpc("create_public_order",{organization_slug:p.organizationSlug,promotion_slug:p.promotionSlug,participant_name:f.get("name"),participant_phone:first,participant_phone_confirmation:confirmation,requested_quota_count:quantity});if(err){setError(err.message);setLoading(false);return}const token=(data as {public_token:string}).public_token;localStorage.setItem(`azurra-order-${token}`,first);router.push(`/pagamento/${token}`)}return <form className={styles.box} onSubmit={submit}><div className={styles.price}><span>Valor da cota</span><strong>{money(p.quotaPrice)}</strong></div><label>Quantas cotas você quer?</label><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,marginBottom:9}}>{[5,10,20].map(n=><button key={n} type="button" onClick={()=>add(n)} disabled={p.disabled||quantity>=p.maximum} style={{minHeight:46,border:0,borderRadius:10,fontSize:16,fontWeight:900}}>+{n}</button>)}</div><div className={styles.counter}><button type="button" onClick={()=>setQuantity(v=>Math.max(p.minimum,v-1))}><Minus/></button><strong>{quantity}</strong><button type="button" onClick={()=>add(1)}><Plus/></button></div><label htmlFor="name">Seu nome</label><input id="name" name="name" minLength={2} maxLength={120} required placeholder="Nome completo"/><label htmlFor="phone">Seu WhatsApp</label><input id="phone" name="phone" inputMode="tel" minLength={10} required placeholder="(83) 99999-9999"/><label htmlFor="phoneConfirmation">Confirme seu WhatsApp</label><input id="phoneConfirmation" name="phoneConfirmation" inputMode="tel" minLength={10} required placeholder="Digite novamente o mesmo número"/><button className={styles.buy} disabled={p.disabled||loading}>{loading?<><LoaderCircle className={styles.spin}/> Reservando...</>:p.disabled?"Cotas esgotadas":`Reservar ${quantity} ${quantity===1?"cota":"cotas"} • ${money(total)}`}</button><small className={styles.hint}>Os números são atribuídos aleatoriamente e ficam vinculados ao WhatsApp confirmado.</small>{error?<div className={styles.error}>{error}</div>:null}</form>}
