"use client";
import {FormEvent,useMemo,useState} from "react";
import {Check,Copy,LoaderCircle,Minus,Plus} from "lucide-react";
import {QRCodeSVG} from "qrcode.react";
import {createClient} from "@/lib/supabase/client";
import styles from "./public-promotion.module.css";
type Props={organizationSlug:string;promotionSlug:string;quotaPrice:number;minimum:number;maximum:number;reservationMinutes:number;disabled:boolean};
type Order={public_token:string;quota_numbers:number[];total_amount:number;pix:{key:string|null;receiver_name:string|null;receiver_city:string|null}};
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const field=(id:string,v:string)=>`${id}${String(v.length).padStart(2,"0")}${v}`;
function crc16(s:string){let crc=0xffff;for(let i=0;i<s.length;i++){crc^=s.charCodeAt(i)<<8;for(let b=0;b<8;b++)crc=(crc&0x8000)?((crc<<1)^0x1021)&0xffff:(crc<<1)&0xffff}return crc.toString(16).toUpperCase().padStart(4,"0")}
function pix(key:string,amount:number,name?:string|null,city?:string|null){const clean=(v:string,f:string,m:number)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^A-Za-z0-9 ]/g,"").toUpperCase().slice(0,m)||f;const merchant=field("00","BR.GOV.BCB.PIX")+field("01",key);const base=field("00","01")+field("26",merchant)+field("52","0000")+field("53","986")+field("54",amount.toFixed(2))+field("58","BR")+field("59",clean(name||"RECEBEDOR","RECEBEDOR",25))+field("60",clean(city||"CIDADE","CIDADE",15))+field("62",field("05","***"))+"6304";return base+crc16(base)}
export function PurchaseForm(p:Props){
 const [quantity,setQuantity]=useState(p.minimum),[loading,setLoading]=useState(false),[error,setError]=useState(""),[order,setOrder]=useState<Order|null>(null),[phone,setPhone]=useState(""),[copied,setCopied]=useState(false),[reported,setReported]=useState(false);
 const total=useMemo(()=>p.quotaPrice*quantity,[p.quotaPrice,quantity]);const payload=order?.pix.key?pix(order.pix.key,Number(order.total_amount),order.pix.receiver_name,order.pix.receiver_city):"";
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const f=new FormData(e.currentTarget);const ph=`+55${String(f.get("phone")||"").replace(/\D/g,"").replace(/^55/,"")}`;setPhone(ph);const {data,error:err}=await createClient().rpc("create_public_order",{organization_slug:p.organizationSlug,promotion_slug:p.promotionSlug,participant_name:f.get("name"),participant_phone:ph,requested_quota_count:quantity});if(err)setError(err.message);else setOrder(data as Order);setLoading(false)}
 async function copy(){await navigator.clipboard.writeText(payload||order?.pix.key||"");setCopied(true);setTimeout(()=>setCopied(false),1500)}
 async function report(){if(!order)return;setLoading(true);const {error:err}=await createClient().rpc("report_public_payment",{order_token:order.public_token,participant_phone:phone,payer_name:null});if(err)setError(err.message);else setReported(true);setLoading(false)}
 if(order)return <section className={styles.box}><div className={styles.success}><Check/> Cotas reservadas por {p.reservationMinutes} minutos</div><div className={styles.numbers}>{order.quota_numbers.map(n=><span key={n}>{n}</span>)}</div><div className={styles.price}><span>Total a pagar</span><strong>{money(Number(order.total_amount))}</strong></div>{payload?<div className={styles.qr}><QRCodeSVG value={payload} size={190}/><small>Leia com o aplicativo do seu banco</small></div>:<div className={styles.error}>A chave PIX ainda não foi configurada.</div>}{order.pix.key?<><label>PIX copia e cola</label><button type="button" className={styles.copy} onClick={copy}><span>{payload||order.pix.key}</span>{copied?<Check/>:<Copy/>}</button></>:null}<button type="button" className={styles.buy} disabled={loading||reported} onClick={report}>{loading?<LoaderCircle className={styles.spin}/>:reported?<><Check/> Pagamento informado</>:"Já fiz o pagamento"}</button>{reported?<p className={styles.notice}>Recebemos seu aviso. O responsável confirmará o pagamento.</p>:null}{error?<div className={styles.error}>{error}</div>:null}</section>;
 return <form className={styles.box} onSubmit={submit}><div className={styles.price}><span>Valor da cota</span><strong>{money(p.quotaPrice)}</strong></div><label>Quantas cotas você quer?</label><div className={styles.counter}><button type="button" onClick={()=>setQuantity(v=>Math.max(p.minimum,v-1))}><Minus/></button><strong>{quantity}</strong><button type="button" onClick={()=>setQuantity(v=>Math.min(p.maximum,v+1))}><Plus/></button></div><label htmlFor="name">Seu nome</label><input id="name" name="name" minLength={2} maxLength={120} required placeholder="Nome completo"/><label htmlFor="phone">Seu WhatsApp</label><input id="phone" name="phone" inputMode="tel" minLength={10} required placeholder="(83) 99999-9999"/><button className={styles.buy} disabled={p.disabled||loading}>{loading?<><LoaderCircle className={styles.spin}/> Reservando...</>:p.disabled?"Cotas esgotadas":`Reservar ${quantity} ${quantity===1?"cota":"cotas"} • ${money(total)}`}</button><small className={styles.hint}>Os números são escolhidos aleatoriamente entre os disponíveis.</small>{error?<div className={styles.error}>{error}</div>:null}</form>
}
